// Built-in parametric controller: a server-authored source TEMPLATE plus its
// parameter space. The optimization loop varies only the NUMBERS defined here;
// the server validates them and renders this fixed template into controller
// source, which is deployed via engine.deployController(). No agent-supplied
// string is ever interpolated — only validated numbers — so the parametric path
// has no code-injection surface.
//
// The default parameters below are a NEUTRAL starting point (a plain PD with
// fixed setpoints, mirroring the naive starter). They are NOT tuned values;
// tuning findings for this rig live only in the fan-control-optimize skill.

export interface ZoneParams {
  spUp: number; // setpoint (°C) applied while temperature is rising
  spDown: number; // setpoint (°C) applied while temperature is falling
  kp: number; // proportional gain on (temp - setpoint)
  kd: number; // derivative gain on smoothed slope
  cap: number; // max rpm for this zone's fans (0..5000)
}

export interface ControllerParams {
  zones: [ZoneParams, ZoneParams];
  emaAlpha: number; // slope smoothing factor (0..1)
  slopeRisingThreshold: number; // slope above which the "rising" setpoint applies
}

// Neutral defaults — the naive starter expressed in the parametric family.
export const DEFAULT_PARAMS: ControllerParams = {
  zones: [
    { spUp: 70, spDown: 70, kp: 200, kd: 0, cap: 5000 },
    { spUp: 60, spDown: 60, kp: 200, kd: 0, cap: 5000 },
  ],
  emaAlpha: 0.5,
  slopeRisingThreshold: 0.05,
};

// Generic search-space bounds (not findings). Fan RPM is hard-capped at 5000.
const ZONE_BOUNDS: Record<keyof ZoneParams, readonly [number, number]> = {
  spUp: [0, 100],
  spDown: [0, 100],
  kp: [0, 2000],
  kd: [0, 5000],
  cap: [0, 5000],
};
const GLOBAL_BOUNDS: Record<'emaAlpha' | 'slopeRisingThreshold', readonly [number, number]> = {
  emaAlpha: [0, 1],
  slopeRisingThreshold: [0, 1],
};

export type ValidationResult =
  | { ok: true; params: ControllerParams }
  | { ok: false; error: string };

const isFiniteNumber = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v);
const inRange = (v: number, [lo, hi]: readonly [number, number]) => v >= lo && v <= hi;

/** Validate arbitrary input as ControllerParams: finite numbers, in-bounds, correct shape. */
export function validateParams(input: unknown): ValidationResult {
  if (typeof input !== 'object' || input === null) {
    return { ok: false, error: 'params must be an object' };
  }
  const p = input as Record<string, any>;
  if (!Array.isArray(p.zones) || p.zones.length !== 2) {
    return { ok: false, error: 'params.zones must be an array of exactly 2 zones' };
  }
  const zones: ZoneParams[] = [];
  for (let z = 0; z < 2; z++) {
    const zp = p.zones[z];
    if (typeof zp !== 'object' || zp === null) {
      return { ok: false, error: `params.zones[${z}] must be an object` };
    }
    const out: any = {};
    for (const key of ['spUp', 'spDown', 'kp', 'kd', 'cap'] as (keyof ZoneParams)[]) {
      const v = zp[key];
      if (!isFiniteNumber(v)) return { ok: false, error: `params.zones[${z}].${key} must be a finite number` };
      if (!inRange(v, ZONE_BOUNDS[key])) {
        return { ok: false, error: `params.zones[${z}].${key}=${v} out of bounds [${ZONE_BOUNDS[key][0]}, ${ZONE_BOUNDS[key][1]}]` };
      }
      out[key] = v;
    }
    zones.push(out);
  }
  for (const key of ['emaAlpha', 'slopeRisingThreshold'] as const) {
    const v = p[key];
    if (!isFiniteNumber(v)) return { ok: false, error: `params.${key} must be a finite number` };
    if (!inRange(v, GLOBAL_BOUNDS[key])) {
      return { ok: false, error: `params.${key}=${v} out of bounds [${GLOBAL_BOUNDS[key][0]}, ${GLOBAL_BOUNDS[key][1]}]` };
    }
  }
  return {
    ok: true,
    params: {
      zones: [zones[0], zones[1]],
      emaAlpha: p.emaAlpha,
      slopeRisingThreshold: p.slopeRisingThreshold,
    },
  };
}

/**
 * Render the fixed controller template with validated NUMBERS only. `params`
 * MUST have passed validateParams first — every value is emitted via String()
 * of a known-finite number, so no arbitrary string can reach the source.
 */
export function renderControllerSource(params: ControllerParams): string {
  const z = params.zones;
  const n = (x: number) => String(Number(x)); // x already validated finite
  return `import type { SimState } from './engine-api.js';
// AUTO-GENERATED by the fan-control MCP server (parametric controller).
// Do not edit by hand — redeployed whenever parameters change.
export function control(state: SimState, context: Record<string, any>): number[] {
  const spUp = [${n(z[0].spUp)}, ${n(z[1].spUp)}];
  const spDown = [${n(z[0].spDown)}, ${n(z[1].spDown)}];
  const kp = [${n(z[0].kp)}, ${n(z[1].kp)}];
  const kd = [${n(z[0].kd)}, ${n(z[1].kd)}];
  const cap = [${n(z[0].cap)}, ${n(z[1].cap)}];
  const emaAlpha = ${n(params.emaAlpha)};
  const slopeRisingThreshold = ${n(params.slopeRisingThreshold)};

  const prev = context.prev ?? state.zones.map(z => z.temp);
  const ema = context.ema ?? state.zones.map(() => 0);
  const slope = state.zones.map((z, i) => emaAlpha * ema[i] + (1 - emaAlpha) * (z.temp - prev[i]));

  const zoneRpm = state.zones.map((z, i) => {
    const rising = slope[i] > slopeRisingThreshold;
    const sp = rising ? spUp[i] : spDown[i];
    const rpm = kp[i] * (z.temp - sp) + kd[i] * slope[i];
    return Math.max(0, Math.min(cap[i], rpm));
  });

  context.prev = state.zones.map(z => z.temp);
  context.ema = slope;
  return state.fans.map((_f, i) => (i < 2 ? zoneRpm[0] : zoneRpm[1]));
}
`;
}

// --- Numeric-vector view of the params, for the optimizer search space. ---

export interface Dimension {
  label: string;
  bounds: readonly [number, number];
}

/** Ordered dimensions of the search space with their bounds. */
export const DIMENSIONS: Dimension[] = [
  { label: 'zones.0.spUp', bounds: ZONE_BOUNDS.spUp },
  { label: 'zones.0.spDown', bounds: ZONE_BOUNDS.spDown },
  { label: 'zones.0.kp', bounds: ZONE_BOUNDS.kp },
  { label: 'zones.0.kd', bounds: ZONE_BOUNDS.kd },
  { label: 'zones.0.cap', bounds: ZONE_BOUNDS.cap },
  { label: 'zones.1.spUp', bounds: ZONE_BOUNDS.spUp },
  { label: 'zones.1.spDown', bounds: ZONE_BOUNDS.spDown },
  { label: 'zones.1.kp', bounds: ZONE_BOUNDS.kp },
  { label: 'zones.1.kd', bounds: ZONE_BOUNDS.kd },
  { label: 'zones.1.cap', bounds: ZONE_BOUNDS.cap },
  { label: 'emaAlpha', bounds: GLOBAL_BOUNDS.emaAlpha },
  { label: 'slopeRisingThreshold', bounds: GLOBAL_BOUNDS.slopeRisingThreshold },
];

export function toVector(p: ControllerParams): number[] {
  return [
    p.zones[0].spUp, p.zones[0].spDown, p.zones[0].kp, p.zones[0].kd, p.zones[0].cap,
    p.zones[1].spUp, p.zones[1].spDown, p.zones[1].kp, p.zones[1].kd, p.zones[1].cap,
    p.emaAlpha, p.slopeRisingThreshold,
  ];
}

export function fromVector(v: number[]): ControllerParams {
  return {
    zones: [
      { spUp: v[0], spDown: v[1], kp: v[2], kd: v[3], cap: v[4] },
      { spUp: v[5], spDown: v[6], kp: v[7], kd: v[8], cap: v[9] },
    ],
    emaAlpha: v[10],
    slopeRisingThreshold: v[11],
  };
}
